services:
  db:
    image: mcr.microsoft.com/mssql/server:2025-latest
    restart: always
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: YourStrong!Passw0rd
    ports:
      - 1433:1433
    volumes:
      - sqldata:/var/opt/mssql

volumes:
  sqldata: