services:
  traefik:
    image: traefik:latest
    restart: unless-stopped
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=paweldywan@paweldywan.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "letsencrypt:/letsencrypt"
    networks:
      - webnet
    labels:
      - "traefik.http.routers.http-catchall.rule=Host(`paweldywan.com`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.redirect.rule=Host(`paweldywan.com`)"
      - "traefik.http.routers.redirect.entrypoints=websecure"
      - "traefik.http.middlewares.redirect-to-github.redirectregex.regex=^https?://(.*)"
      - "traefik.http.middlewares.redirect-to-github.redirectregex.replacement=https://github.com/paweldywan"
      - "traefik.http.routers.redirect.middlewares=redirect-to-github"
      - "traefik.http.routers.redirect.tls.certresolver=myresolver"
networks:
  webnet:
    external: true

volumes:
  letsencrypt:
